apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 3
  minReadySeconds: 10  # wait for 10 seconds
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - image: nginx:1.19-alpine
        name: sample-app
        resources:
          limits:
            memory: "16Mi"
            cpu: "100m"
