apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 10
      periodSeconds: 5
      failureThreshold: 1

# livenessProbe checks /index.html on port 80
# waits 15 seconds
# timeout after 5 seconds
# check every 5 seconds
# Allow 1 failure before failing the pod

######## How to test liveness probe? ##########
# kubectl apply -f nginx_pod_liveness_probe.yaml
# kubectl exec -it my-nginx sh
# rm -f /usr/share/nginx/html
# You will be kicked out of the pod
# Inspect pod events by using describe
# kubectl describe pod my-nginx
#################################################
